// Export utility functions for generating CSV/reports and downloading files

export function downloadCSV(data: Record<string, any>[], filename: string, columns?: { key: string; label: string }[]) {
  const keys = columns ? columns.map(c => c.key) : Object.keys(data[0] || {});
  const headers = columns ? columns.map(c => c.label) : keys;
  
  const csvRows = [
    headers.join(','),
    ...data.map(row => 
      keys.map(key => {
        const val = row[key];
        const str = val === null || val === undefined ? '' : String(val);
        return str.includes(',') || str.includes('"') ? `"${str.replace(/"/g, '""')}"` : str;
      }).join(',')
    )
  ];
  
  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
}

export function downloadJSON(data: any, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  triggerDownload(blob, `${filename}_${new Date().toISOString().split('T')[0]}.json`);
}

export function downloadTextReport(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  triggerDownload(blob, `${filename}_${new Date().toISOString().split('T')[0]}.txt`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateInvoiceReport(bill: any): string {
  return `
╔══════════════════════════════════════════════════════╗
║               MEDFLOW GENERAL HOSPITAL               ║
║                    INVOICE                            ║
╠══════════════════════════════════════════════════════╣
║ Invoice ID: ${bill.id}
║ Date: ${new Date().toLocaleDateString()}
║ Patient: ${bill.patientName}
║ Patient ID: ${bill.patientId}
║ Due Date: ${bill.dueDate}
╠══════════════════════════════════════════════════════╣
║ SERVICES:
${bill.items?.map((item: any) => `║   ${item.description.padEnd(35)} $${item.amount.toFixed(2)}`).join('\n') || '║   No items'}
╠══════════════════════════════════════════════════════╣
║ TOTAL: $${bill.amount?.toFixed(2) || '0.00'}
║ STATUS: ${bill.status?.toUpperCase() || 'PENDING'}
╚══════════════════════════════════════════════════════╝
`;
}

export function generateShiftReport(patients: any[], shift: any): string {
  return `
═══════════════════════════════════════════════
       SHIFT HANDOVER REPORT
       MedFlow General Hospital
═══════════════════════════════════════════════
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}
Nurse: ${shift?.nurse || 'Current Nurse'}
Shift: ${shift?.shift || 'Day Shift'}
═══════════════════════════════════════════════

PATIENT OVERVIEW:
${patients.map((p, i) => `
${i + 1}. ${p.name} - Room ${p.room || 'N/A'}
   Condition: ${p.condition || 'N/A'}
   Vitals: Temp ${p.vitals?.temp || 'N/A'}, BP ${p.vitals?.bp || 'N/A'}, HR ${p.vitals?.hr || 'N/A'}, SpO2 ${p.vitals?.spo2 || 'N/A'}
   Tasks: ${p.tasks?.join(', ') || 'None pending'}
`).join('')}

CRITICAL UPDATES:
- All patients stable unless noted above
- Medication schedules on track
- No new admissions expected

PENDING TASKS FOR NEXT SHIFT:
- Complete routine vitals checks
- Administer scheduled medications
- Update patient charts

═══════════════════════════════════════════════
Report generated by MedFlow HMS
═══════════════════════════════════════════════
`;
}

export function generateComplianceReport(audits: any[]): string {
  return `
═══════════════════════════════════════════════
       COMPLIANCE AUDIT REPORT
       MedFlow General Hospital
═══════════════════════════════════════════════
Date: ${new Date().toLocaleDateString()}
Generated by: MedFlow HMS

AUDIT SUMMARY:
${audits.map((a, i) => `
${i + 1}. ${a.type}
   Status: ${a.status?.toUpperCase()}
   Score: ${a.score}%
   Last Check: ${a.lastCheck}
   Next Due: ${a.nextDue}
`).join('')}

OVERALL COMPLIANCE: ${Math.round(audits.reduce((s: number, a: any) => s + (a.score || 0), 0) / audits.length)}%

═══════════════════════════════════════════════
`;
}

export function generateMedicationReport(medications: any[]): string {
  return `
═══════════════════════════════════════════════
       MEDICATION REPORT
       MedFlow General Hospital
═══════════════════════════════════════════════
Date: ${new Date().toLocaleDateString()}

ACTIVE MEDICATIONS:
${medications.map((m, i) => `
${i + 1}. ${m.medication || m.name}
   Patient: ${m.patientName || m.patient}
   Dosage: ${m.dosage}
   Frequency: ${m.frequency}
   Prescribed by: ${m.doctor || m.prescriber}
   Status: ${m.status}
`).join('')}

Total Active: ${medications.filter(m => m.status === 'active').length}
Total Completed: ${medications.filter(m => m.status === 'completed').length}

═══════════════════════════════════════════════
`;
}

export function generateBillingReport(bills: any[]): string {
  const total = bills.reduce((s, b) => s + (b.amount || 0), 0);
  const paid = bills.filter(b => b.status === 'paid').reduce((s, b) => s + (b.amount || 0), 0);
  const pending = bills.filter(b => b.status === 'pending').reduce((s, b) => s + (b.amount || 0), 0);
  
  return `
═══════════════════════════════════════════════
       FINANCIAL REPORT
       MedFlow General Hospital
═══════════════════════════════════════════════
Date: ${new Date().toLocaleDateString()}

SUMMARY:
  Total Revenue: $${total.toFixed(2)}
  Collected: $${paid.toFixed(2)}
  Outstanding: $${pending.toFixed(2)}
  Collection Rate: ${total > 0 ? ((paid / total) * 100).toFixed(1) : 0}%

BILL DETAILS:
${bills.map((b, i) => `
${i + 1}. ${b.patientName} - $${b.amount?.toFixed(2)} [${b.status?.toUpperCase()}]
   Due: ${b.dueDate}
`).join('')}

═══════════════════════════════════════════════
`;
}
